TarimCan/Controllers/GenelSinavController.cs
using System.Web.Mvc;
using TarimCan.DataAccessLayer;
using TarimCan.Models;

namespace TarimCan.Controllers
{
    public class GenelSinavController : Controller
    {
        CommonManager cm = new CommonManager();

        // GET: GenelSinav
        public ActionResult Index()
        {
            Response.Headers.Remove("X-Frame-Options");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public JsonResult TcKimlikNodanSinavSorgula(long TCKimlikNo)
        {
            SiteResponseModel srm = new SiteResponseModel();
            SinavSonucuModel ssm = cm.SinavSonucuGetir(TCKimlikNo);

            if (ssm != null)
            {
                srm.IsSuccess = true;
                srm.Message = " Sayın <strong> " + ssm.AdiSoyadi + " </strong> <br /> <br /> Durumunuz: " + ssm.Durumu;

                //srm.Message = " Sayın <strong> " + ssm.AdiSoyadi + " </strong> <br /> <br /> Almış olduğunuz sınav sonucunuz: <strong>" + ssm.SinavSonucu + "</strong> <br /> Başarı Durumunuz: " + ssm.Durumu;

                if (ssm.Durumu == "BAŞARILI")
                {
                    srm.Message += "<br /><br /><a href=\"" + ssm.SertifikaPath + "\" target=\"_blank\"> Sertifikanızı indirmek için tıklayınız...</a>";
                }

            }
            else
            {
                srm.IsSuccess = false;
                srm.Message = "Sınav sonucu bulunamadı... Lütfen bilgilerinizi kontrol ediniz...";
            }
            return Json(srm);
        }

    }
}

TarimCan/Views/GenelSinav/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8" />
    <title>Tarım Can Yeni Nesil Çiftlik Yardımcınız</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="tarimcan, terra seracılık, terra bilişim, sürü yönetimi, çiftlik yönetimi, sera yönetimi, yazılım program" />
    <meta content="" name="Terra Bilişim Hizmetleri" />
    <!-- BEGIN GLOBAL MANDATORY STYLES

    <link href="../DashboardTheme/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/global/plugins/font-awesome/css/font-awesome.min.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/global/plugins/simple-line-icons/simple-line-icons.min.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/global/plugins/bootstrap/css/bootstrap.min.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/global/plugins/uniform/css/uniform.default.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/global/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/global/plugins/fullcalendar/fullcalendar.min.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/global/plugins/jqvmap/jqvmap/jqvmap.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/admin/pages/css/tasks.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/global/plugins/select2/select2.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/global/css/components-rounded.css")" type="text/css" id="style_components" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/global/css/plugins.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/admin/layout4/css/layout.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/admin/layout4/css/themes/light.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/admin/layout4/css/custom.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/DashboardTheme/assets/admin/pages/css/profile.css")" type="text/css" />

    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.2.0/css/all.css" type="text/css" />

</head>

<body class="page-header-fixed page-sidebar-closed-hide-logo page-sidebar-closed-hide-logo">

    <div class="page-content-wrapper" style="margin-top: -10px !important;">
        <div class="row">

            <div class="col-md-12">
                <div class="portlet light">
                    <div class="portlet-body form">
                        <!-- BEGIN FORM-->
                        <div class="form-horizontal">

                            <div class="form-group">
                                <label class="col-md-3 control-label">TC Kimlik Numarası</label>
                                <div class="col-md-4">
                                    <input type="number" class="form-control" placeholder="TC Kimlik No" id="TCKimlikNo" autocomplete="off" tabindex="3" maxlength="11" min="1" max="99999999999" oninput="maxLengthCheck(this)">
                                </div>
                            </div>

                            <div class="form-group" id="dvSuccess" style="display:none">
                                <label class="col-md-3 control-label">&nbsp;</label>
                                <div class="col-md-4">
                                    <div class="alert alert-info" id="dvSuccessMessage" style="margin-bottom: 0px;">

                                    </div>
                                </div>
                            </div>

                            <div class="form-group" id="dvError" style="display:none">
                                <label class="col-md-3 control-label">&nbsp;</label>
                                <div class="col-md-4">
                                    <div class="alert alert-danger" id="dvErrorMessage" style="margin-bottom: 0px;">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-3 control-label">&nbsp;</label>
                                <div class="col-md-4">
                                    <button id="btnSosYardOde" type="submit" class="btn green" onclick="Sorgula()" style="width:100%">Sorgula</button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                @Html.AntiForgeryToken()
            </div>
        </div>
        <a href="javascript:;" class="page-quick-sidebar-toggler"><i class="icon-login"></i></a>
    </div>

    <link href="@Url.Content("~/DashboardTheme/assets/admin/layout4/css/custom.css")" type="text/css" rel="stylesheet" />
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jquery.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jquery-migrate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jquery-ui/jquery-ui.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/bootstrap/js/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jquery.blockui.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jquery.cokie.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/uniform/jquery.uniform.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jqvmap/jqvmap/jquery.vmap.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jquery.sparkline.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/select2/select2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/bootbox/bootbox.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/global/scripts/metronic.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/DashboardTheme/assets/admin/layout4/scripts/layout.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jquery.min.js")" type="text/javascript"></script>
    <script src="https://use.fortawesome.com/1ce05b4b.js"></script>

    <script>


        $(document).ready(function () {
            document.body.style.backgroundColor = "white";
        });

        function Sorgula() {

            document.getElementById("dvSuccess").style.display = 'none';
            document.getElementById("dvError").style.display = 'none';

            var TCKimlikNo = document.getElementById("TCKimlikNo").value;

            console.log(document.getElementById("TCKimlikNo").lenght);
            console.log(TCKimlikNo);
            console.log(Object.keys(TCKimlikNo).length);

            if (TCKimlikNo == "") {
                ShowInfoFunctionBox("TC Kimlik Numaranızı Giriniz...");
                return;
            }

            if (Object.keys(TCKimlikNo).length != 11) {
                ShowInfoFunctionBox("TC Kimlik No 11 Karakter olmalıdır...");
                return;
            }

            var dataObject = (
            {
                __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val(),
                'TCKimlikNo': TCKimlikNo
            });

            $.ajax({
                type: "POST",
                url: '@Url.Action("TcKimlikNodanSinavSorgula", "GenelSinav")',
                data: dataObject,
                success: function (response) {
                    console.log(JSON.stringify(response));
                    if (response.IsSuccess) {
                        document.getElementById("dvSuccess").style.display = 'block';
                        document.getElementById("dvSuccessMessage").innerHTML = response.Message;
                    }
                    else {
                        document.getElementById("dvError").style.display = 'block';
                        document.getElementById("dvErrorMessage").innerHTML = response.Message;

                    }
                }
            });

        }

        function maxLengthCheck(object) {
            if (object.value.length > object.maxLength)
                object.value = object.value.slice(0, object.maxLength)
        }

        function isNumeric(evt) {
            var theEvent = evt || window.event;
            var key = theEvent.keyCode || theEvent.which;
            key = String.fromCharCode(key);
            var regex = /[0-9]|\./;
            if (!regex.test(key)) {
                theEvent.returnValue = false;
                if (theEvent.preventDefault) theEvent.preventDefault();
            }
        }

        function GoToProfile() {
            location.href = "/Profil/Index";
        }

        function LogOut() {
            location.href = "/Home/LogOut";
        }

        function ShowErrorMessageBox(message) {
            bootbox.dialog({
                message: message,
                title: "Hata !", buttons: {
                    danger: { label: "Tamam", className: "red" }
                }
            });
        }

        function ShowInfoFunctionBox(message) {
            bootbox.dialog({
                message: message,
                title: "Bilgi !", buttons: {
                    danger: { label: "Tamam", className: "orange" }
                }
            });
        }

    </script>
</body>
<!-- END BODY -->
</html>