TarimCan/Controllers/TempController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TarimCan.Helper;
using TarimCan.Models;

namespace TarimCan.Controllers
{
    public class TempController : BaseController
    {
        // GET: Temp
        [UserAuthorizeController]
        public ActionResult Index()
        {
            return View();
        }

        [UserAuthorizeController]
        public ActionResult AnahtarKelimeGirisi()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public JsonResult AnahtarKelimeKaydet(AnahtarKelimeModel model)
        {
            SiteResponseModel srm = new SiteResponseModel();

            DBCheckModel dbC = cm.AnahtarKelimeKaydet(model, SessionManager.KullaniciId, helper.GetIPAddress());
            if (dbC.ReturnValue == 1)
            {
                srm.IsSuccess = true;
                srm.Message = "Kayıt başarılı...";
            }
            else if (dbC.ReturnValue == 2)
            {
                srm.IsSuccess = false;
                srm.Message = "Anahtar kelime girişi daha önce yapılmış...";
            }
            else
            {
                srm.IsSuccess = false;
                srm.Message = "Kayıt sırasında hata oluştu...";
            }

            return Json(srm, JsonRequestBehavior.AllowGet);
        }
    }
}

TarimCan/Views/Temp/AnahtarKelimeGirisi.cshtml
@using TarimCan.Models
@using TarimCan.Helper

@{
    ViewBag.Title = "Anahtar Kelime";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="portlet light bordered">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-equalizer font-green-sharp"></i>
                <span class="caption-subject font-green-sharp bold uppercase">ANAHTAR KELİME GİRİŞİ</span>
            </div>
        </div>
        <div class="portlet-body form" style="min-height: 619px;">
            <!-- BEGIN FORM-->
            <div class="form-horizontal">
                <div class="form-body">

                    <div class="alert alert-danger">
                        <strong>Uyarı!</strong> Cevabı kaydetmeniz durumunda, Girmiş olduğunuz yanıt değiştirilemeyecektir.
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">İsim Soyisim</label>
                        <div class="col-md-5">
                            <input type="text" id="IsimSoyisim" class="form-control" placeholder="konu başlığı" autocomplete="off" maxlength="100" value="@SessionManager.IsimSoyisim" disabled>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label"><b>Anahtar Kelime</b></label>
                        <div class="col-md-5">
                            <input type="text" id="AnahtarKelime" class="form-control" placeholder="anahtar kelime" autocomplete="off" maxlength="100">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">Görüş ve Önerileriniz</label>
                        <div class="col-md-5">
                            <textarea class="form-control" rows="7" id="GorusVeOneri" placeholder="görüş ve öneri" maxlength="1000"></textarea>
                        </div>
                    </div>

                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <button type="submit" class="btn green" onclick="Kaydet()">Anahtar Kelime Kaydet</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END FORM-->
        </div>
        @Html.AntiForgeryToken()
    </div>
</div>

<script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jquery.min.js")" type="text/javascript"></script>

<script>


    function Kaydet() {

        var AnahtarKelime = document.getElementById("AnahtarKelime").value;
        var GorusVeOneri = document.getElementById("GorusVeOneri").value;

        var datassss = (
            {
                __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val(),
                'AnahtarKelime': AnahtarKelime,
                'GorusVeOneri': GorusVeOneri
            });

        //console.log("datassss: " + JSON.stringify(datassss));


        if (AnahtarKelime == "" || GorusVeOneri == "") {
            ShowInfoFunctionBox("Lütfen tüm alanları doldurunuz...");
            return;
        }

        var data = (
        {
            __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val(),
            'AnahtarKelime': AnahtarKelime,
            'GorusVeOneri': GorusVeOneri
        });

        //console.log("dataObject: " + JSON.stringify(data));

        $.ajax({
            type: "POST",
            url: '@Url.Action("AnahtarKelimeKaydet", "Temp")',
            data: data,
            success: function (response) {
                //console.log("Response: " + JSON.stringify(response))
                if (response.IsSuccess) {
                    ShowInfoFunctionBox(response.Message);
                }
                else {
                    ShowErrorMessageBox(response.Message);
                }
            }
        });

    }

</script>

<script>
    $('#AnahtarKelimeMenu').addClass("active");
</script>