TarimCan/Controllers/HayvanlarController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using TarimCan.Helper;
using TarimCan.Models;

namespace TarimCan.Controllers
{
    public class HayvanlarController : BaseController
    {

        [UserAuthorizeController]
        public ActionResult Index(int SuruGrubuId = 0, int HayvanId = 0, int DurumOzetiId = 0, int PadokId = 0)
        {

            if (PadokId != 0)
            {
                List<HayvanModel> hayvanlar = new List<HayvanModel>();
                hayvanlar = hm.SurudekiHayvanlariPadogaGoreGetir(PadokId, SessionManager.KullaniciId);
                ViewBag.Hayvanlar = hayvanlar;
                ViewBag.DurumBilgileri = cm.TumDurumBilgileriniGetir();
                ViewBag.SuruGruplari = cm.TumSuruGruplariniGetir();
                ViewBag.SuruGrubuId = SuruGrubuId;
                ViewBag.HayvanSayisi = hayvanlar.Count;

                ViewBag.DurumOzetiId = DurumOzetiId;
                ViewBag.SuruGrubuId = SuruGrubuId;

                return View();
            }

            if (SuruGrubuId != 0)
            {
                ViewBag.SayfaBasligi = cm.SuruGrubuSayfaBasligiGetir(SuruGrubuId).Value;
            }
            else if (DurumOzetiId != 0)
            {
                ViewBag.SayfaBasligi = cm.DurumOzetiSayfaBasligiGetir(DurumOzetiId).Value;
            }
            else
            {
                ViewBag.SayfaBasligi = "Hayvan";
            }

            if (HayvanId == 0)
            {
                List<HayvanModel> hayvanlar = new List<HayvanModel>();
                hayvanlar = hm.SurudekiHayvanlariSahibineGoreGetir(SessionManager.KullaniciId, SuruGrubuId, DurumOzetiId);
                ViewBag.Hayvanlar = hayvanlar;
                ViewBag.DurumBilgileri = cm.TumDurumBilgileriniGetir();
                ViewBag.SuruGruplari = cm.TumSuruGruplariniGetir();
                ViewBag.SuruGrubuId = SuruGrubuId;
                ViewBag.HayvanSayisi = hayvanlar.Count;

                if (hayvanlar.Count == 1)
                {
                    ViewBag.CinsiyetId = hayvanlar[0].CinsiyetId;
                    ViewBag.HayvanId = hayvanlar[0].Id;
                }
                else
                {
                    ViewBag.CinsiyetId = 0;
                    ViewBag.HayvanId = 0;
                }
            }
            else
            {
                List<HayvanModel> hayvan = new List<HayvanModel>();
                hayvan.Add(hm.HayvanDetayiSahibineGoreGetir(HayvanId, SessionManager.KullaniciId));
                ViewBag.Hayvanlar = hayvan;
                ViewBag.CinsiyetId = hayvan[0].CinsiyetId;
                ViewBag.DurumBilgileri = cm.TumDurumBilgileriniGetir();
                ViewBag.SuruGruplari = cm.TumSuruGruplariniGetir();
                ViewBag.HayvanSayisi = 1;
                ViewBag.HayvanId = HayvanId;

                if (hayvan.Count == 1)
                {
                    ViewBag.CinsiyetId = hayvan[0].CinsiyetId;
                    ViewBag.HayvanId = hayvan[0].Id;
                }
                else
                {
                    ViewBag.CinsiyetId = 0;
                    ViewBag.HayvanId = 0;
                }
            }

            ViewBag.DurumOzetiId = DurumOzetiId;
            ViewBag.SuruGrubuId = SuruGrubuId;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public JsonResult HayvanDetayGetir(int HayvanId)
        {
            HayvanDetayResponseModel model = new HayvanDetayResponseModel();

            model.HayvanDetay = hm.HayvanDetayiSahibineGoreGetir(HayvanId, SessionManager.KullaniciId);
            model.DurumHareketleri = hm.HayvanDurumHareketleriGetir(HayvanId, SessionManager.KullaniciId);

            ViewBag.Fotograflar = model.HayvanDetay.Fotograflar;

            if (model != null)
            {
                model.IsSuccess = true;
            }
            else
            {
                model.IsSuccess = false;
                model.Message = "Hayvan bulunamadı...";
            }

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public JsonResult HayvanDurumHareketleriGetirAction(int HayvanId)
        {
            List<DurumHareketModel> list = hm.HayvanDurumHareketleriGetir(HayvanId, SessionManager.KullaniciId);

            HayvanDetayResponseModel model = new HayvanDetayResponseModel();
            if (model != null)
            {
                model.IsSuccess = true;
                model.DurumHareketleri = list;
            }
            else
            {
                model.IsSuccess = false;
                model.Message = "Hareket bulunamadı...";
            }

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [UserAuthorizeController]
        public ActionResult HayvanEkle(int DurumId, int HayvanId)
        {
            int HayvanKacAylik = 0;
            ViewBag.Cinsiyeti = cm.TumHayvanCinsiyetleriniGetir();
            ViewBag.Irki = cm.TumHayvanIrklariniGetir();
            ViewBag.SuruyeGirisTipi = cm.TumSuruyeGirisTipleriniGetir();
            ViewBag.SuruyeGirisDurumlari = cm.TumSuruyeGirisDurumlariGetir();
            ViewBag.Padoklar = cm.IsletmeyeGorePadokGetir(SessionManager.KullaniciId);

            ViewBag.HayvanId = HayvanId;
            ViewBag.DurumId = DurumId;
            ViewBag.BabaKupeNo = "";
            if (hm.SonEklenenIrkIdGetir(SessionManager.KullaniciId) != null)
            {
                ViewBag.SonEklenenIrkId = hm.SonEklenenIrkIdGetir(SessionManager.KullaniciId).IrkId;
            }
            else
            {
                ViewBag.SonEklenenIrkId = 0;
            }

            if (HayvanId == 0)
            {
                ViewBag.IslemTipi = 1; //Ekle
                return View();
            }
            else if (DurumId != 0 && HayvanId != 0)
            {
                HayvanModel hayMod = hm.HayvanDetayiSahibineGoreGetir(HayvanId, SessionManager.KullaniciId);
                ViewBag.AnneKupeNo = hayMod.KupeNo;

                HayvanModel BabaKupeNoModel = hm.TohumlananBabaKupeNoGetir(HayvanId, SessionManager.KullaniciId);
                if (BabaKupeNoModel != null)
                {
                    ViewBag.BabaKupeNo = BabaKupeNoModel.BabaKupeNo;
                }
                else
                {
                    ViewBag.BabaKupeNo = "";
                }
                ViewBag.IrkId = hayMod.IrkId;
                ViewBag.IslemTipi = 1; //Ekle
                return View();
            }
            else
            {
                HayvanModel hayMod = hm.HayvanDetayiSahibineGoreGetir(HayvanId, SessionManager.KullaniciId);
                ViewBag.IrkId = hayMod.IrkId;
                ViewBag.SuruyeGirisTipId = hayMod.SuruyeGirisTipId;
                ViewBag.CinsiyetId = hayMod.CinsiyetId;
                ViewBag.Fotograf = hayMod.Fotograf;
                ViewBag.PhotoCount = hayMod.Fotograflar.Count;
                ViewBag.IslemTipi = 2; //Güncelle

                TimeSpan HayvanGun = DateTime.Now - hayMod.DogumTarihi;
                ViewBag.HayvanKacAylik = HayvanGun.Days / 30;

                return View(hayMod);
            }
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken()]
        //public JsonResult HayvanEkleAction(HayvanModel model)
        //{
        //    SiteResponseModel srm = new SiteResponseModel();

        //    try
        //    {
        //        if (SessionManager.HayvanTohumlamaAyi != 0)
        //        {

        //            model.Fotograf = helper.TopluHayvanResmiKaydet(model);

        //            DBCheckModel dbC = hm.HayvanKaydet(model);
        //            if (dbC.ReturnValue == 1)
        //            {

        //                hm.HayvanSuruGruplariniGuncell();
        //                srm.IsSuccess = true;
        //                srm.Message = "Kayıt başarılı...";
        //            }
        //            else if (dbC.ReturnValue == 2)
        //            {
        //                srm.IsSuccess = false;
        //                srm.Message = dbC.ReturnMessage;
        //            }
        //            else
        //            {
        //                srm.IsSuccess = false;
        //                srm.Message = "Kayıt sırasında hata oluştu...";
        //            }
        //        }
        //        else
        //        {
        //            srm.IsSuccess = false;
        //            srm.Message = "Hayvan tohumlama başlangıç ayı girilmeli...";
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        srm.IsSuccess = false;
        //        srm.MessageCode = -1;
        //        srm.Message = ex.ToString();
        //    }

        //    return Json(srm, JsonRequestBehavior.AllowGet);
        //}


        [HttpPost]
        [ValidateAntiForgeryToken()]
        public JsonResult HayvanEkleAction(HayvanModel model)
        {
            SiteResponseModel srm = new SiteResponseModel();

            try
            {
                if (SessionManager.HayvanTohumlamaAyi != 0)
                {

                    model.Fotograf = helper.TopluHayvanResmiKaydet(model.Foto1Base64, model.Foto2Base64, model.Foto3Base64, model.Foto4Base64);

                    DBCheckModel dbC = hm.HayvanKaydet(model, SessionManager.KullaniciId);
                    if (dbC.ReturnValue == 1)
                    {
                        int KayitEdilenHayvanId = Convert.ToInt32(dbC.ReturnMessage);
                        DurumHareketModel dhm = new DurumHareketModel();
                        int DogumdanItibarenGecenGunSayisi = 0;

                        hm.HayvanSuruGruplariniGuncell(SessionManager.KullaniciId);

                        if (model.SonDogumYaptigiTarih.Year != 9999)
                        {
                            // Hayvan doğum kaydı ekleniyor...

TarimCan/Views/Hayvanlar/BosHayvanlar.cshtml
@using TarimCan.Models

@{
    ViewBag.Title = "Hayvanlarım";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/DashboardTheme/LightBox/css/lightbox.css" rel="stylesheet" />

<div class="col-md-12" style="min-height:600px">

    <div class="portlet light bordered" style="min-height:620px">
        <div class="portlet light" style="padding:0 !important; font-size:13px !important; margin:0px !important">
            <div class="portlet-title" style="margin-bottom:0px !important">
                <div class="caption">
                    <i class="icon-equalizer font-red-sunglo"></i>
                    <span class="caption-subject font-red-sunglo bold uppercase" style="font-size:15px">BOŞTAKİ HAYVANLAR</span> -
                    <a href="https://www.youtube.com/watch?v=Zm51mv885aI&t=83s" target="_blank"> <img src="~/DashboardTheme/assets/global/ana-icons/youtube-full-logo.png" style="height:20px" title="Yardım Videosu"></a>
                </div>

                <div class="actions">
                    <a href="/Hayvanlar/HayvanEkle?DurumId=0&HayvanId=0" class="btn btn-circle btn-default">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-480">
                            Hayvan Ekle
                        </span>
                    </a>
                </div>
            </div>
        </div>
        <div class="portlet-body">
            @{
                if (ViewBag.Hayvanlar != null)
                {

                    List<HayvanModel> hayvanlar = ViewBag.Hayvanlar;

                    if (hayvanlar.Count > 0)
                    {

                        <table class="table table-hover table-light">
                            <thead>
                                <tr>
                                    <th style="text-align:center">Detay</th>
                                    <th style="text-align:center">No</th>
                                    <th style="text-align:center">Küpe No</th>
                                    <th style="text-align:center">Adı / Takip Numarası</th>
                                    <th style="text-align:center">Yaşı</th>
                                    <th style="text-align:center">Son Doğum Yaptığı Tarih</th>
                                    <th style="text-align:center">Son Doğumu Güç Mü?</th>
                                    <th style="text-align:center">Son Doğumda Eşini / Sonunu Attı Mı?</th>
                                    <th style="text-align:center">SGS</th>
                                    <th style="text-align:center">Tohum Başarı Oranı</th>
                                </tr>
                                <tr role="row" class="filter">
                                    <td rowspan="1" colspan="1" style="text-align:center; cursor:pointer">
                                        <button class="btn btn-sm yellow filter-submit margin-bottom" onclick="HayvanFiltrele()"><i class="fa fa-search"></i>&nbsp; Ara</button>
                                    </td>
                                    <td rowspan="1" colspan="1">
                                        &nbsp;
                                    </td>
                                    <td rowspan="1" colspan="1">
                                        <input type="text" class="form-control form-filter input-sm" id="flKupeNo" placeholder="küpe no">
                                    </td>
                                    <td rowspan="1" colspan="1">
                                        <input type="text" class="form-control form-filter input-sm" id="flAdi" placeholder="adı">
                                    </td>
                                    <td rowspan="1" colspan="1">
                                        <input type="text" class="form-control form-filter input-sm" disabled>
                                    </td>
                                    <td rowspan="1" colspan="1">
                                        <input type="text" class="form-control form-filter input-sm" disabled>
                                    </td>
                                    <td rowspan="1" colspan="1">
                                        <input type="text" class="form-control form-filter input-sm" disabled>
                                    </td>
                                    <td rowspan="1" colspan="1">
                                        <input type="text" class="form-control form-filter input-sm" disabled>
                                    </td>
                                    <td rowspan="1" colspan="1">
                                        <input type="text" class="form-control form-filter input-sm" disabled>
                                    </td>
                                    <td rowspan="1" colspan="1">
                                        <input type="text" class="form-control form-filter input-sm" disabled>
                                    </td>
                                </tr>
                            </thead>
                            <tbody id="tblHayvanResult">
                                @{
                                    int sayacSos = 1;

                                    foreach (var item in hayvanlar)
                                    {
                                        <tr>
                                            <td style="text-align:center; cursor:pointer">
                                                <a class="label label-sm label-info" href="/Hayvanlar/HayvanDetay/@item.Id"> Detay </a>
                                            </td>
                                            <td style="text-align:center">@Convert.ToInt32(sayacSos++).ToString()</td>
                                            <td>
                                                @item.KupeNo
                                            </td>
                                            <td>
                                                @item.Adi
                                            </td>
                                            <td style="text-align:center">
                                                @{
                                                    TimeSpan ts = DateTime.Now - item.DogumTarihi;

                                                    int gunSayisi = ts.Days;
                                                    decimal dcYilSayisi = gunSayisi / 365;
                                                    int intYilSayisi = Convert.ToInt32(Math.Floor(dcYilSayisi));

                                                    int yilGunu = intYilSayisi * 365;
                                                    int kalan = gunSayisi - yilGunu;

                                                    decimal dcAySayisi = kalan / 30;
                                                    int intAySayisi = Convert.ToInt32(Math.Floor(dcAySayisi));

                                                    string YilStr = Convert.ToInt32(Math.Floor(dcYilSayisi)).ToString() + " Yaş ";
                                                    string AyStr = Convert.ToInt32(Math.Floor(dcAySayisi)).ToString() + " Ay";

                                                    <span>
                                                        @if (intYilSayisi != 0)
                                                        {
                                                            @YilStr
                                                        }

                                                        @if (intAySayisi != 0)
                                                        {
                                                            @AyStr
                                                        }
                                                    </span>
                                                }
                                            </td>
                                            <td style="text-align:center">
                                                @if (item.SonDogumYaptigiTarihFormatted != "01.01.9999")
                                                {
                                                    @item.SonDogumYaptigiTarihFormatted
                                                }
                                            </td>
                                            <td style="text-align:center">
                                                @if (item.SonDogumYaptigiTarihFormatted != "01.01.9999")
                                                {
                                                    if (item.DogumGucMu)
                                                    {
                                                        <span>Evet</span>
                                                    }
                                                    else
                                                    {
                                                        <span>Hayır</span>
                                                    }
                                                }
                                            </td>
                                            <td style="text-align:center">
                                                @if (item.SonDogumYaptigiTarihFormatted != "01.01.9999")
                                                {
                                                    if (item.EsiniSonunuAttiMi)
                                                    {
                                                        <span>Evet</span>
                                                    }
                                                    else
                                                    {
                                                        <span>Hayır</span>
                                                    }
                                                }
                                            </td>
                                            <td style="text-align:center">
                                                @item.SGS
                                            </td>
                                            <td style="text-align:center">
                                                @item.TohumTutmaOrani
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <span>Listelenecek hayvan bulunamadı...</span>
                    }
                }
                else
                {
                    <span>Listelenecek hayvan bulunamadı...</span>
                }
            }
        </div>
    </div>
    @Html.AntiForgeryToken()
</div>

<script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jquery.min.js")" type="text/javascript"></script>

<script src="~/DashboardTheme/LightBox/js/lightbox.js"></script>

<script>

    function GoToHayvanGuncelle() {
        location.href = "/Hayvanlar/HayvanEkle?DurumId=0&HayvanId=" + document.getElementById("hdnHayvanId").value;
    }

    function validate(evt) {
        var theEvent = evt || window.event;

        // Handle paste
        if (theEvent.type === 'paste') {
            key = event.clipboardData.getData('text/plain');
        } else {
            // Handle key press
            var key = theEvent.keyCode || theEvent.which;
            key = String.fromCharCode(key);
        }
        var regex = /[0-9]|\./;
        if (!regex.test(key)) {
            theEvent.returnValue = false;
            if (theEvent.preventDefault) theEvent.preventDefault();
        }
    }

    function HayvanFiltrele() {
        var strKupeNo = $("#flKupeNo").val();
        var strAdi = $("#flAdi").val();
        var strAciklama = $("#flAciklama").val();

        var data = {
            __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val(),
            'KupeNo': strKupeNo,
            'Adi': strAdi,
            'Aciklama': strAciklama,
            'SuruGrubuId': document.getElementById("SuruGruplari").value,
            'CinsiyetId': document.getElementById("flCinsiyet").value
        };

        $.ajax({
            type: "POST",
            url: '@Url.Action("HayvanAraAction", "Hayvanlar")',
            data: data,
            success: function (response) {
                document.getElementById("tblHayvanResult").innerHTML = "";
                var sayac = 0;
                for (var k in response) {
                    sayac = sayac + 1;
                    $('#tblHayvanResult').append('<tr><td> <a class="label label-sm label-info" href="/Hayvanlar/HayvanDetay/' + response[k].Id +'"> Detay </a> </td><td>' + sayac + '</td> <td>' + response[k].KupeNo + '</td> <td>' + response[k].Adi + '</td> <td>' + response[k].SuruGrubu + '</td> <td>' + response[k].Cinsiyet + '</td> ');
                    //$('#tblHayvanResult').append('<tr><td>' + sayac + '</td> <td>' + response[k].KupeNo + '</td> <td>' + response[k].Adi + '</td> <td>' + response[k].SuruyeGirisTarihiFormatted + '</td> <td>' + response[k].SuruGrubu + '</td> <td>' + response[k].Cinsiyet + '</td>  <td>' + response[k].DogumTarihiFormatted + '</td> <td><span class="label label-sm label-info" onclick="HayvanDetayGetir(' + response[k].Id + ')"> Detay </span> </td>');
                }
            }
        });
    }

</script>

<script>
    $('#HayvanYonetimi').addClass("active");
</script>

TarimCan/Views/Hayvanlar/HastalikEkle.cshtml
@using TarimCan.Models
@using TarimCan.Helper

@{
    ViewBag.Title = "Hastalık Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="portlet light bordered minHeight">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-equalizer font-green-sharp"></i>
                <span class="caption-subject font-green-sharp bold uppercase">HASTALIK EKLE</span> -
                <a href="https://www.youtube.com/watch?v=Zm51mv885aI&t=83s" target="_blank"> <img src="~/DashboardTheme/assets/global/ana-icons/youtube-full-logo.png" style="height:20px" title="Yardım Videosu"></a>
            </div>
        </div>
        <div class="portlet-body form">
            <!-- BEGIN FORM-->
            <div class="form-horizontal">
                @{

                    <div class="form-group">
                        <label class="col-md-3 control-label">İşlem Tarihi</label>
                        <div class="col-md-4">
                            <input type="date" class="form-control" data-format="00-00-0000" placeholder="dd-mm-yyyy" id="IslemTarihi" autocomplete="off">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">Hastalık</label>
                        <div class="col-md-4">
                            @Html.DropDownList("Hastaliklar", new SelectList(ViewBag.Hastaliklar, "Value", "Text"), "Seçiniz", new { @class = "form-control", @onchange = "HastalikChanged(this.value)" })
                        </div>
                    </div>

                    <div class="form-group" id="rwDiger" style="display:none">
                        <label class="col-md-3 control-label">Hastalık Adı</label>
                        <div class="col-md-4">
                            <input type="text" class="form-control" placeholder="hastalık adı" id="DigerHastalik">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">Kullanılan İlaç</label>
                        <div class="col-md-4">
                            <input type="text" class="form-control" placeholder="kullanılan ilaç" id="KullanilanIlac">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">İlaç Maliyeti</label>
                        <div class="col-md-4">
                            <input type="number" class="form-control" placeholder="ilaç fiyatı" id="IlacMaliyeti" value="0">
                        </div>
                    </div>

                    <div class="form-group" id="rwKesimKarkasAgirlik">
                        <label class="col-md-3 control-label">Veteriner Hekim</label>
                        <div class="col-md-4">
                            <input type="text" class="form-control" placeholder="veteriner hekim" id="VeterinerHekim">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">Veteriner Hekim Maliyeti</label>
                        <div class="col-md-4">
                            <input type="number" class="form-control" placeholder="veteriner hekim maliyeti" id="VeterinerHekimMaliyeti" value="0">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">Açıklama</label>
                        <div class="col-md-4">
                            <textarea class="form-control" id="Aciklama" cols="5"></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">&nbsp;</label>
                        <div class="col-md-4">
                            <button id="btnSosYardOde" type="submit" class="btn green" onclick="Kaydet()" style="width:100%">Durum Bilgisi Kaydet</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    @Html.AntiForgeryToken()
</div>

<script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jquery.min.js")" type="text/javascript"></script>

<script>

    $(function () {
        const queryString = window.location.search;
        const urlParams = new URLSearchParams(queryString);
        const IslemTarihi = urlParams.get('IslemTarihi')
        document.getElementById("IslemTarihi").value = IslemTarihi;
    })

    function formatMoney(price) {
        var currency_symbol = "₺"
        var formattedOutput = new Intl.NumberFormat('tr-TR', {
            style: 'currency',
            currency: 'TRY',
            minimumFractionDigits: 2,
        });
        return formattedOutput.format(price).replace(currency_symbol, '')
    }

    function HastalikChanged(val) {

        console.log("val: " + val);

        document.getElementById("rwDiger").style.display = 'none';

        if (val == 18) {
            document.getElementById("rwDiger").style.display = 'block';
        }

    }

    function Kaydet() {

        var Aciklama = "";

        console.log("Ölüm Açıklama: " + Aciklama);

        var data = {
            __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val(),
            'HayvanId': @ViewBag.HayvanId,
            'DurumBilgisiId': 2,
            'IslemTarihi': document.getElementById("IslemTarihi").value,
            'HastalikId': document.getElementById("Hastaliklar").value,
            'KullanilanIlac': document.getElementById("KullanilanIlac").value,
            'KullanilanIlacMaliyeti': document.getElementById("IlacMaliyeti").value,
            'VeterinerHekim': document.getElementById("VeterinerHekim").value,
            'VeterinerHekimMaliyeti': document.getElementById("VeterinerHekimMaliyeti").value,
            'Aciklama': document.getElementById("Aciklama").value,
            'DigerHastalik': document.getElementById("DigerHastalik").value
        };

        console.log("data", JSON.stringify(data));

        $.ajax({
            type: "POST",
            url: '@Url.Action("HastalikEkleAction", "Hayvanlar")',
            data: data,
            success: function (response) {
                if (response.IsSuccess) {
                    bootbox.dialog({
                        message: "İşlem başarılı",
                        title: "İşlem Tamamlandı. Kayıt Başarılı.",
                        buttons: {
                            success: {
                                label: "Tamam",
                                className: "green",
                                callback: function () {
                                    location.href = "/Hayvanlar/Index/";
                                }
                            }
                        }
                    });
                }
                else {
                    if (response.MessageCode != -1) {
                        ShowInfoFunctionBox(response.Message);
                    }
                    else {
                        console.log(response.Message);
                    }
                }
            }
        });
    }

</script>

<script>

    function maxLengthCheck(object) {
        if (object.value.length > object.maxLength)
            object.value = object.value.slice(0, object.maxLength)
    }

    function isNumeric(evt) {
        var theEvent = evt || window.event;
        var key = theEvent.keyCode || theEvent.which;
        key = String.fromCharCode(key);
        var regex = /[0-9]|\./;
        if (!regex.test(key)) {
            theEvent.returnValue = false;
            if (theEvent.preventDefault) theEvent.preventDefault();
        }
    }

</script>

<script>
    $('#HayvanEkle').addClass("active");
</script>