TarimCan/Controllers/TanimlamalarController.cs
using System.Web.Mvc;
using TarimCan.Models;

namespace TarimCan.Controllers
{
    public class TanimlamalarController : BaseController
    {
        [UserAuthorizeController]
        public ActionResult Index()
        {
            return View();
        }

        [UserAuthorizeController]
        public ActionResult HayvanIrklari()
        {
            return View(tm.TumHayvanIrklariniGetir());
        }

        [UserAuthorizeController]
        public JsonResult HayvanIrklariAction(int IslemId, int Id, string Value)
        {
            //DBCheckModel model = new DBCheckModel();

            DBCheckModel model = tm.HayvanIrkıIslemleri(IslemId, Id, Value);

            if (model.ReturnValue == 1)
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }
        }

        [UserAuthorizeController]
        public ActionResult SuruGruplari()
        {
            return View(tm.TumHayvanSuruGruplariniGetir());
        }

        [UserAuthorizeController]
        public JsonResult SuruGruplariAction(int IslemId, int Id, string Value)
        {
            //DBCheckModel model = new DBCheckModel();

            DBCheckModel model = tm.HayvanSuruGrubuIslemleri(IslemId, Id, Value);

            if (model.ReturnValue == 1)
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }
        }

        [UserAuthorizeController]
        public ActionResult RutinIslemler()
        {
            ViewBag.DurumBilgileri = cm.TumDurumBilgileriniGetir();
            return View();
        }


        [UserAuthorizeController]
        [HttpPost]
        public JsonResult RutinIslemlerAction(int DurumBilgisiId)
        {
            return Json(tm.RutinIslemiDurumTipineGoreGetir(DurumBilgisiId));
        }

        [UserAuthorizeController]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public JsonResult RutinIslemEkleAction(RutinIslemModel model)
        {
            //DBCheckModel model = new DBCheckModel();

            //DBCheckModel dbc = tm.RutinIslemEkle(model);

            //if (dbc.ReturnValue == 1)
            //{
            //    return Json(true);
            //}
            //else
            //{
            //    return Json(false);
            //}
            return Json(false);
        }

        [UserAuthorizeController]
        public ActionResult DurumBilgisi()
        {
            return View();
        }

        [UserAuthorizeController]
        public ActionResult HayvanStatuleri()
        {
            return View();
        }
    }
}

TarimCan/Views/Tanimlamalar/DurumBilgisi.cshtml
@{
    ViewBag.Title = "DurumBilgisi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DurumBilgisi</h2>

TarimCan/Views/Tanimlamalar/HayvanIrklari.cshtml
@using TarimCan.Models

@model List<IdValueModel>

@{
    ViewBag.Title = "Hayvan Irkları";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="portlet light bordered">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-equalizer font-red-sunglo"></i>
                <span class="caption-subject font-red-sunglo bold uppercase">HAYVAN IRKI TANIMLARI</span>
            </div>
        </div>
        <div class="portlet-body form">
            <div class="form-horizontal">
                <div class="form-body">

                    <div class="form-group">
                        <label class="col-md-3 control-label">Hayvan Irkı</label>
                        <div class="col-md-4">
                            <input type="text" id="txtValue" class="form-control" placeholder="hayvan ırkı" autocomplete="off">
                        </div>
                    </div>

                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <button type="submit" class="btn green" onclick="Kaydet()">Kaydet</button>
                            <button type="button" class="btn default" onclick="Temizle()">Temizle</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-9">
                <div class="portlet box red-intense">
                    <div class="portlet-title">
                        <div class="caption" style="padding-top:15px">
                            <i class="fa fa-globe"></i>Hayvan Irkı
                        </div>
                        <div class="tools">
                            <button type="button" class="btn default" onclick="YeniKayitTalep()">Yeni Kayıt</button>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div id="sample_1_wrapper" class="dataTables_wrapper no-footer">
                            <div class="table-scrollable">
                                <table class="table table-striped table-bordered table-hover dataTable no-footer">
                                    <thead>
                                        <tr role="row">
                                            <th>
                                                Id
                                            </th>
                                            <th>
                                                Hayvan Irkı
                                            </th>
                                            <th>

                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @item.Id
                                                </td>
                                                <td>
                                                    @item.Value
                                                </td>
                                                <td>
                                                    <a href="javascript:;" class="btn default btn-xs green-stripe" onclick="GuncelleTalep('@item.Id', '@item.Value')"> Güncelle </a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <input type="hidden" id="hdnId" value="0" />
        <input type="hidden" id="hdnIslem" value="1" />

    </div>
</div>

<script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jquery.min.js")" type="text/javascript"></script>

<script>

    function GuncelleTalep(DemirbasId, DemirbasYeri) {
        document.getElementById("txtValue").value = DemirbasYeri;
        document.getElementById("hdnId").value = DemirbasId;
        document.getElementById("hdnIslem").value = 2;
    }

    function YeniKayitTalep() {
        document.getElementById("txtValue").value = '';
        document.getElementById("hdnId").value = 0;
        document.getElementById("hdnIslem").value = 1;
    }

    function Kaydet() {

        //console.log('IslemId :' + document.getElementById("hdnIslem").value);
        //console.log('Id :' + document.getElementById("hdnId").value);
        //console.log('Value :' + document.getElementById("txtValue").value);

        var dataObject = JSON.stringify(
        {
            'IslemId': document.getElementById("hdnIslem").value,
            'Id': document.getElementById("hdnId").value,
            'Value': document.getElementById("txtValue").value
        });

        $.ajax({
            type: "POST",
            url: '@Url.Action("HayvanIrklariAction", "Tanimlamalar")',
            contentType: 'application/json',
            data: dataObject,
            success: function (response) {
                if (response) {
                    location.reload();
                }
                else {
                    ShowErrorMessageBox('Hata Oluştu...');
                }
            },
            error: function () {
            },
            beforeSend: function () {
            },
            complete: function () {
            }
        });
    }
</script>

<script>
    $('#tanimlamalar').addClass("open");
    $('#tanimlamalarArrow').addClass("open");
    $('#tanimlamalarSubMenu').css("display", "block");
    $('#subMenuHayvanIrklari').addClass("active");
</script>

TarimCan/Views/Tanimlamalar/HayvanStatuleri.cshtml
@{
    ViewBag.Title = "HayvanStatuleri";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>HayvanStatuleri</h2>

TarimCan/Views/Tanimlamalar/RutinIslemler.cshtml
@using TarimCan.Models

@{
    ViewBag.Title = "Rutin İşlemler";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="portlet light bordered">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-equalizer font-red-sunglo"></i>
                <span class="caption-subject font-red-sunglo bold uppercase">RUTİN İŞLEM TANIMLARI</span>
            </div>
        </div>
        <div class="portlet-body form">
            <div class="form-horizontal">
                <div class="form-body">

                    <div class="form-group">
                        <label class="col-md-3 control-label">Durum Bilgisi</label>
                        <div class="col-md-4">
                            @Html.DropDownList("DurumBilgisiId", new SelectList(ViewBag.DurumBilgileri, "Value", "Text"), "Seçiniz", new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">Rutin İşlem</label>
                        <div class="col-md-4">
                            <input type="text" id="txtRutinIslem" class="form-control" placeholder="rutin işlem" autocomplete="off">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">İşlem Yapılacak Süre</label>
                        <div class="col-md-4">
                            <input type="number" id="txtIslemSure" class="form-control" placeholder="işlem yapılacak süre" autocomplete="off">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">&nbsp;</label>
                        <div class="col-md-4">
                            <input type="checkbox" id="chkVeterinerGerekiyorMu" name="chkVeterinerGerekiyorMu">
                            <label for="chkVeterinerGerekiyorMu">Veteriner kontrolü gerekiyor mu?</label>
                        </div>
                    </div>

                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <button type="submit" class="btn green" onclick="Kaydet()">Kaydet</button>
                            <button type="button" class="btn default" onclick="Temizle()">Temizle</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-9">
                <div class="portlet box red-intense">
                    <div class="portlet-title">
                        <div class="caption" style="padding-top:15px">
                            <i class="fa fa-globe"></i>Durum Bilgisi
                        </div>
                        <div class="tools" style="margin-left:15px">
                            <button type="button" class="btn default" onclick="YeniKayitTalep()">Yeni Kayıt</button>
                        </div>
                        <div class="tools">
                            @Html.DropDownList("DurumBilgileri", new SelectList(ViewBag.DurumBilgileri, "Value", "Text"), "Seçiniz", new { @class = "form-control", @onchange = "DurumBilgisiChanged(this.value)" })
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div id="sample_1_wrapper" class="dataTables_wrapper no-footer">
                            <div class="table-scrollable">
                                <table class="table table-striped table-bordered table-hover dataTable no-footer">
                                    <thead>
                                        <tr role="row">
                                            <th>
                                                Id
                                            </th>
                                            <th>
                                                İşlem Adı
                                            </th>
                                            <th>
                                                Süre
                                            </th>
                                            <th>
                                                Veteriner Gerekiyor Mu
                                            </th>
                                            @*<th>
                                                    &nbsp;
                                                </th>*@
                                        </tr>
                                    </thead>
                                    <tbody id="tblResult">
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <input type="hidden" id="hdnId" value="0" />
        <input type="hidden" id="hdnIslem" value="1" />

    </div>

    @Html.AntiForgeryToken()
</div>

<script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jquery.min.js")" type="text/javascript"></script>

<script>

    function Kaydet() {
        var DurumBilgisiId = document.getElementById("DurumBilgisiId").value;
        var RutinIslem = document.getElementById("txtRutinIslem").value;
        var DogumdanSonrakiSure = document.getElementById("txtIslemSure").value;
        var VeterinerKontroluGerekiyorMu = document.getElementById("chkVeterinerGerekiyorMu").checked;

        if (DurumBilgisiId == "" || RutinIslem == "" || DogumdanSonrakiSure == "") {
            ShowErrorMessageBox('Tüm alanları doldurunuz.');
            return;
        }

        var dataObject = (
        {
            __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val(),
            'DurumBilgisiId': DurumBilgisiId,
            'RutinIslem': RutinIslem,
            'DogumdanSonrakiSure': DogumdanSonrakiSure,
            'VeterinerKontroluGerekiyorMu': VeterinerKontroluGerekiyorMu
        });
 

        $.ajax({
            type: "POST",
            url: '@Url.Action("RutinIslemEkleAction", "Tanimlamalar")',
            data: dataObject,
            success: function (response) {
                if (response) {
                    document.getElementById("DurumBilgisiId").value = "";
                    document.getElementById("txtIslemSure").value = "";
                    document.getElementById("txtRutinIslem").value = "";
                    document.getElementById("chkVeterinerGerekiyorMu").checked = false;
                    ShowInfoFunctionBox('Kayıt Başarılı');
                }
                else {
                    ShowErrorMessageBox('Hata Oluştu...');
                }
            },
            error: function () {
            },
            beforeSend: function () {
            },
            complete: function () {
            }
        });
    }

    function DurumBilgisiChanged(val) {

       // console.log("val: " + val);

        var dataObject = JSON.stringify({
            'DurumBilgisiId': val,
        });

        $.ajax({
            type: "POST",
            url: '@Url.Action("RutinIslemlerAction", "Tanimlamalar")',
            contentType: 'application/json',
            data: dataObject,
            success: function (response) {
                document.getElementById("tblResult").innerHTML = "";
                var sayac = 0;
                for (var k in response) {
                    sayac = sayac + 1;
                    $('#tblResult').append('<tr><td>' + sayac + '</td> <td>' + response[k].RutinIslem + '</td> <td>' + response[k].DogumdanSonrakiSure + '</td> <td>' + response[k].VeterinerKontroluGerekiyorMu + '</td>');
                    //$('#tblResult').append('<tr><td>' + sayac + '</td> <td>' + response[k].RutinIslem + '</td> <td>' + response[k].DogumdanSonrakiSure + '</td> <td>' + response[k].VeterinerKontroluGerekiyorMu + '</td> ' +
                    //    '<td><span class="label label-sm label-info" onclick="GuncelleTalep(' + response[k].DurumBilgisiId + ', ' + response[k].DogumdanSonrakiSure + ', \'' + response[k].RutinIslem + '\', ' + response[k].VeterinerKontroluGerekiyorMu + ')"> Detay </span> </td>');
                }
            }
        });
    }

    function GuncelleTalep(DurumBilgisiId, IslemSure, RutinIslem, VetKontrolGerekiyorMu) {
        document.getElementById("DurumBilgisiId").value = DurumBilgisiId;
        document.getElementById("txtIslemSure").value = IslemSure;
        document.getElementById("txtRutinIslem").value = RutinIslem;

        if (VetKontrolGerekiyorMu) {
            document.getElementById("chkVeterinerGerekiyorMu").checked = true;
        }
        else {
            document.getElementById("chkVeterinerGerekiyorMu").checked = false;
        }
    }

    function YeniKayitTalep() {
        document.getElementById("txtValue").value = '';
        document.getElementById("hdnId").value = 0;
        document.getElementById("hdnIslem").value = 1;
    }

</script>

<script>
    $('#tanimlamalar').addClass("open");
    $('#tanimlamalarArrow').addClass("open");
    $('#tanimlamalarSubMenu').css("display", "block");
    $('#subMenuHayvanIrklari').addClass("active");
</script>

TarimCan/Views/Tanimlamalar/SuruGruplari.cshtml
@using TarimCan.Models

@model List<IdValueModel>

@{
    ViewBag.Title = "Hayvan Sürü Grupları";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="portlet light bordered">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-equalizer font-red-sunglo"></i>
                <span class="caption-subject font-red-sunglo bold uppercase">SÜRÜ GRUBU TANIMLARI</span>
            </div>
        </div>
        <div class="portlet-body form">
            <div class="form-horizontal">
                <div class="form-body">

                    <div class="form-group">
                        <label class="col-md-3 control-label">Sürü Grubu</label>
                        <div class="col-md-4">
                            <input type="text" id="txtValue" class="form-control" placeholder="sürü grubu" autocomplete="off">
                        </div>
                    </div>

                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <button type="submit" class="btn green" onclick="Kaydet()">Kaydet</button>
                            <button type="button" class="btn default" onclick="Temizle()">Temizle</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-9">
                <div class="portlet box red-intense">
                    <div class="portlet-title">
                        <div class="tools">
                            <button type="button" class="btn default" onclick="YeniKayitTalep()">Yeni Kayıt</button>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div id="sample_1_wrapper" class="dataTables_wrapper no-footer">
                            <div class="table-scrollable">
                                <table class="table table-striped table-bordered table-hover dataTable no-footer">
                                    <thead>
                                        <tr role="row">
                                            <th>
                                                Id
                                            </th>
                                            <th>
                                                Sürü Grubu
                                            </th>
                                            <th>

                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @item.Id
                                                </td>
                                                <td>
                                                    @item.Value
                                                </td>
                                                <td>
                                                    <a href="javascript:;" class="btn default btn-xs green-stripe" onclick="GuncelleTalep('@item.Id', '@item.Value')"> Güncelle </a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <input type="hidden" id="hdnId" value="0" />
        <input type="hidden" id="hdnIslem" value="1" />

    </div>
</div>

<script src="@Url.Content("~/DashboardTheme/assets/global/plugins/jquery.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/app-custom.js")" type="text/javascript"></script>

<script>

    function GuncelleTalep(DemirbasId, DemirbasYeri) {
        document.getElementById("txtValue").value = DemirbasYeri;
        document.getElementById("hdnId").value = DemirbasId;
        document.getElementById("hdnIslem").value = 2;
    }

    function YeniKayitTalep() {
        document.getElementById("txtValue").value = '';
        document.getElementById("hdnId").value = 0;
        document.getElementById("hdnIslem").value = 1;
    }

    function Kaydet() {

        //console.log('IslemId :' + document.getElementById("hdnIslem").value);
        //console.log('Id :' + document.getElementById("hdnId").value);
        //console.log('Value :' + document.getElementById("txtValue").value);

        var dataObject = JSON.stringify(
        {
            'IslemId': document.getElementById("hdnIslem").value,
            'Id': document.getElementById("hdnId").value,
            'Value': document.getElementById("txtValue").value
        });

        $.ajax({
            type: "POST",
            url: '@Url.Action("SuruGruplariAction", "Tanimlamalar")',
            contentType: 'application/json',
            data: dataObject,
            success: function (response) {
                if (response) {
                    location.reload();
                }
                else {
                    ShowErrorMessageBox('Hata Oluştu...');
                }
            },
            error: function () {
            },
            beforeSend: function () {
            },
            complete: function () {
            }
        });

    }
</script>

<script>
    $('#tanimlamalar').addClass("open");
    $('#tanimlamalarArrow').addClass("open");
    $('#tanimlamalarSubMenu').css("display", "block");
    $('#subMenuSuruGruplari').addClass("active");
</script>